# -*- coding: utf-8 -*-
# AUTO-GENERATED from GameFAQs FAQ 51436 (dante_croft) by tools/kof_convert.py
ATHENA_MATCHUPS = [
    ('Kyo', '9/10', 'Pressure him with many Psycho Ball Attacks and several crouching C. Attack him constantly.'),
    ('Iori', '7.5/10', 'Beware with his jumps,’cuz Iori has the advantage. Do many crouching C can- celled in Psycho Ball Attack. Try to confuse him with the teleport and if he jump, use Athena’s SCB DM or LDM.'),
    ('Shingo', '8/10', 'Fight against him like you do with Kyo. But don’t forget his special throw!'),
    ('Ash', '8/10', 'Use her Phoenyx Arrow often. Caution with his fireball and his special throw.Try to keep distance with Athena’s fireball.'),
    ('Oswald', '7/10', 'Oswald is one of the most strong characters in the game, but don’t panic! Keep distance and abuse of her psycho ball attack. Fight him only with DM bars in stock, ’cuz Oswald’s moves are really cheap!'),
    ('Shen', '9/10', 'As Shen is slow, abuse of her fireball. Keep distance and use it!If he approaches, use her crouching C or A to put him away.'),
    ('K´', '8.5/10', 'K’is fast, consequently use only low jumps on him. In an aerial dispute, use her Phoenyx Bomb. Don’t forget: If he attack too much, do a SCB DM or her LDM.'),
    ('Maxima', '9.5/10', 'Maxima is strong, but he is slow. Don’t stand stopped! Run, jump, do fireballs,use her teleport. If he approaches jump to far and continue the strategy.'),
    ('Kula', '6.5/10', 'VERY difficult battle...Kula has a high priority in air and her combos are fast!Abuse of Athena’s crouching C, because it is only move that has a tenuous priority against Kula’s moves. Caution with your Psycho Ball Attack, ’cuz Kula revert fireballs. And she does that very fast!!'),
    ('B.Jenet', '?/10', 'Only keep distance and do several fireballs. If she jump, use SCB DM or LDM. If she roll, run and do Athena’s crouching C or Link Kick. Chance of victory: 7/10.'),
    ('Gato', '7/10', 'Ohouuu...Gato is very cheap in ground, then, try keep the fight on air, abusing of Phoenix Bomb and Phoenix Arrow.Only caution with his anti-air Danger move.'),
    ('Tyzoc', '?/10', 'Use the same tatic used against Maxima. Chance of victory:9.5/10.'),
    ('Terry', '8/10', 'Use his slow jump against him, abusing of her jump+C/D,fireballs and teleports.When he be confused and jump, do her SCB DM or LDM.'),
    ('Duck King', '?/10', 'I don’t have much experience against him...Treat him like other enemies without fireballs.'),
    ('Kim', '1.5/10', 'Keep distance!!!!If he approaches, jump back with her Phoenyx Arrow. In corner use the triangular jump to escape. Don’t let him near you because Kim moves have a high priority on the ground.'),
    ('Vanessa', '8/10', 'Use the same tatic use against Kim, but caution doing Athena’s fireball: Vanessa has several moves to beat it. But you too has a trick on sleeve: the Link Kick has a high priority against some Vanessa’s moves.'),
    ('Blue Mary', '8/10', 'Don’t abuse of Athena’s fireball or Mary’ll start a killer combo! Mary doesn’t have fireballs or large ranged attacks, then, wait until she jump or attack nearby and do SCB DM or LDM.'),
    ('Ramon', '7/10', 'Ramon is a throw character.But a fast one!In the air forget Athena’s Phoenyx Arrow because of Ramon’s special throw. It’s very cheap and has a high priority on the ground. Keep medium distance. Not too far, not too near.'),
    ('Elisabeth', '7.5/10', 'Like Kim and Vanessa, her moves on ground are really cheap and have a high priority.Then, abuse of low jumps with D and crouching C, because these moves have a advantage against Elisabeth’s special moves. Only caution with her LDM!'),
    ('Duo Lon', '8.5/10', 'Duolon is strong, but kinda slow. Use her fireball of medium distance and jump often because Duolon doesn’t have a great anti air, only his DM.'),
    ('Benimaru', '8/10', 'Keep doing Athena’s fireball. One time Benimaru’ll jump. Then, do SCB DM or LDM.If he don’t jump, use Athena’s crouching C.'),
    ('Athena', '10/10', 'Interesting battle. Try to keep your reflex focused and when Athena attack, do your SCB DM or LDM.'),
    ('Kensou', '8.5/10', 'Keep near!!Do a crouching C cancelled in a fireball. Do again. And again. If he be desperate and roll or jump, use SCB DM or LDM.'),
    ('Momoko', '9/10', 'Use Athena’s Phoenyx Arrow, and her DM Phoenyx Fang Arrow often, ’cause Momoko doesn’t have any fast move to counter attack.'),
    ('Kasumi', '8/10', 'Only watch out her counter moves. Keep distance and use Athena’s triangular jump if you was cornered.Try to decease her, using Athena’s teleport and her Super Psychic Throw.'),
    ('Malin', '7/10', 'Malin is pretty fast, consequently watch out her!Don’t abuse of fireballs! Try keep near, using low jumps. He she attack too much, use SCB DM or LDM.'),
    ('Eiji', '5.5/10', 'A complex fight...Eiji has high priority on ground and on air!Try move with caution and wait for a error.Use Athena’s crouching C until Eiji do a mistake. Then, use a powerful combo and cause the bigger possible damage.'),
    ('Whip', '8/10', 'Try to keep the fight on air. Caution using fireball, cause Whip is fast and has several combos.'),
    ('Clark', '8.5/10', 'Use the same tatic used against Maxima and Tyzoc.But watch out Clark’s speed, he isn’t so slow.'),
    ('Ralph', '8/10', 'Ralph has excellent normal moves on ground and on air. Jump with caution, or Athena’ll be catch by Ralph’s punches and kicks.Try to keep him far doing fireballs and using her trick back,back, Phoenyx Bomb.'),
    ('Ryo', '8/10', 'Only watch out his uppercut, because it’s very strong!Try to deceive him with Athena’s teleport and wait for a mistake.Don’t forget: Athena can reflect his Haoshokouken.'),
    ('Yuri', '7/10', 'Danger!! Trouble! Trouble!Like Ralph, Yuri has excellent normal moves on ground and on air. But Yuri has fireballs too: on ground and on air...A good trick against Yuris that abuse of her aerial fireball is counter attack with Athena’s DM Shinning Crystal Bit.Like her brother,caution with her uppercut too, it’s very strong!Phoenyx Bomb or aerial throw is a good way of win aerial disputes.'),
    ('King', '8/10', 'Abuse of Athena’s Phoenyx Bomb ’cuz it has priority against the King’s anti-air move (QCB+ B or D).Remember too that King doesn’t have more her special throw. Keep near!'),
    ('Hotaru', '7.5/10', 'Keep near, attacking constantly. Hotaru’s uppercut don’t have the same power ithad in Garou. Jump on her! Only watch out her LDM.'),
    ('Robert', '8.5/10', 'Robert has nice special moves, but lacks on normal moves (are too slow). Then,keep near, doing low jumps followed by crouching C, cancelled in fireball.'),
    ('Tung Fu Rue', '8.5/10', 'This old man is a strong one!He has many anti-air attacks, consequently, try don’t jump. Abuse of Athena’s fireball, ’cuz Tung is fast, but don’t have a long range jump.'),
    ('Hayate', '7/10', 'He is a very strong character. He’s very fast. Try deceive him and wait for a mistake. Athena’s Psycho Reflector doesn’t work against him.'),
    ('Mr. Big', '9/10', 'The Big Chief is strong, but slow.Use it in your help. Keep Mai running, doing katchosens and ryuembus.Jump on him with Mussassabi no Mai, ’cuz his anti-air attacks are ineffective against it.'),
    ('Geese', '8/10', 'Like Kasumi, watch out his counter-moves.Deceive him with teleports, doing him miss his counter moves.'),
    ('Gai', '7/10', 'Keep distance!Keep distance! Did you understand? If he approaches, use Athena’s trick back,back+ Phoenyx Bomb. If you was cornered, use Triangular jump.The Gai’s moves are very cheap and have a high priority.'),
    ('Jazu', '8.5/10', 'Use her Phoenyx Arrow move often, ’cuz jazu is slow .But caution with his uppercut: a really cheap move.'),
    ('Adel', '8/10', 'Adel has slow moves, consequently abuse of crouching C cancelled in fireball. If he approaches too much, use Athena’s teleport.'),
    ('Silver', '8/10', 'Another slow-strong character. Keep moving and don’t let approaches you!'),
    ('EX Kyo', '8/10', 'Use the same tatic used against normal Kyo. They are a bit different, but at the same time, very similar.'),
    ('Mai', '7/10', 'Keep caution against Mai’s jumps!Fight her when you have DM bars in stock.'),
    ('Shion', '6.5/10', 'Well, if the opponent won’t do the infinite combo is a geat start yet. Like against Mai, figh her when you have DM bars in stock.'),
    ('Magaki', '?/10', 'Who’ll choose a boss in a challenger?I don’t know what say about this situation... Maybe a bit of luck? Try to make him miss some moves and do a powerful combo.'),
]
