# -*- coding: utf-8 -*-
# AUTO-GENERATED from GameFAQs FAQ 44220 (RTorrez) by tools/kof_convert.py — do not hand-edit.
def _load(C):
    return [
        C('bnb', 'Normal chain', 'cA > cA', '2h', 1),
        C('bnb', 'Rolling Thunder', 'cA > cA > df+D', '4h', 1),
        C('bnb', 'The Hind', 'cA > cA > @hind.B', '5h', 1),
        C('super', 'Many Torpedo', 'cA > cA > @torpedo', '9h', 1),
        C('super', 'Aurora', 'cA > cA > @aurora', '12h', 1),
        C('dc', 'DC → An Oi', 'cA > cA > @torpedo (DC) > @anoi', '16h', 3),
        C('bnb', 'Normal chain', 'cB > cB', '2h', 1),
        C('bnb', 'Rolling Thunder', 'cB > cB > df+D', '4h', 1),
        C('bnb', 'The Hind', 'cB > cB > @hind.B', '5h', 1),
        C('super', 'Many Torpedo', 'cB > cB > @torpedo', '9h', 1),
        C('super', 'Aurora', 'cB > cB > @aurora', '12h', 1),
        C('dc', 'DC → An Oi', 'cB > cB > @torpedo (DC) > @anoi', '16h', 3),
        C('bnb', 'Normal chain', 'cB > cB > cB', '2h', 1),
        C('bnb', 'The Hind', 'cB > cB > cB > @hind.B > (C)', '6h', 1),
        C('dc', 'DC → An Oi', 'cB > cB > cB > @torpedo (DC) > @anoi', '17h', 3),
        C('bnb', 'Normal chain', 'cB > cB > sB', '3h', 1),
        C('bnb', 'The Hind', 'sA > sA > sA > @hind.B', '6h', 1),
        C('super', 'Many Torpedo', 'sA > sA > sA > @torpedo', '10h', 1),
        C('super', 'Aurora', 'sA > sA > sA > @aurora', '13h', 1),
        C('dc', 'DC → An Oi', 'sA > sA > sA > @torpedo (DC) > @anoi', '17h', 3),
        C('bnb', 'Rolling Thunder', 'sA > sC > df+D', '4h', 1),
        C('bnb', 'Crazy Ivan', 'sA > sC > @ivan.A', '3h', 1),
        C('super', 'Many Torpedo', 'sA > sC > @ivan.A (SC) > @torpedo > (C)', '10h', 2),
        C('super', 'Aurora', 'sA > sC > @ivan.A (SC) > @aurora > (C)', '13h', 2),
        C('dc', 'DC → An Oi', 'sA > sC > @ivan.A (SC) > @torpedo (DC) > @anoi > (C)', '17h', 3),
        C('bnb', 'The Hind', 'sA > sC > @hind.B', '5h', 1),
        C('bnb', 'The Hind', 'sA > sC > @hind.D', '6h', 1),
        C('chain', 'Harrier loop', 'sA > sC > @hind.D > @harrier.D', '7h', 2),
        C('chain', 'Harrier loop', 'sA > sC > @hind.D > @harrier.D', '9h', 2),
        C('corner', 'Rolling Thunder', 'sA > sC > @hind.D (2) > @harrier.D > df+D > (C)', '6h', 2),
        C('corner', 'The Hind', 'sA > sC > @hind.D (2) > @harrier.D > @hind.B > (C)', '6h', 2),
        C('super', 'Many Torpedo', 'sA > sC > @hind.D (2) > @harrier.D > @torpedo', '11h', 2),
        C('super', 'Aurora', 'sA > sC > @hind.D (2) > @harrier.D > @aurora > (C)', '15h', 2),
        C('dc', 'DC → An Oi', 'sA > sC > @hind.D (2) > @harrier.D > @torpedo (DC) > @anoi', '18h', 3),
        C('bnb', 'Gulf Tomahawk', 'sA > sC > @gulf.B', '4h', 1),
        C('super', 'Many Torpedo', 'sA > sC > @torpedo', '9h', 1),
        C('super', 'Aurora', 'sA > sC > @aurora', '12h', 1),
        C('dc', 'DC → An Oi', 'sA > sC > @torpedo (DC) > @anoi', '16h', 3),
        C('bnb', 'The Hind', 'sB > @hind.B', '4h', 1),
        C('super', 'Many Torpedo', 'sB > @torpedo', '8h', 1),
        C('super', 'Aurora', 'sB > @aurora', '12h', 1),
        C('dc', 'DC → An Oi', 'sB > @torpedo (DC) > @anoi', '15h', 3),
        C('bnb', 'Crazy Ivan', 'sC > @ivan.A', '2h', 1),
        C('super', 'Many Torpedo', 'sC > @ivan.A (SC) > @torpedo', '9h', 2),
        C('super', 'Aurora', 'sC > @ivan.A (SC) > @aurora', '12h', 2),
        C('dc', 'DC → An Oi', 'sC > @ivan.A (SC) > @torpedo (DC) > @anoi > (C)', '16h', 3),
        C('bnb', 'Gulf Tomahawk', 'sC > @gulf.B', '3h', 1),
        C('bnb', 'The Hind', 'sC > @hind.B', '4h', 1),
        C('bnb', 'The Hind', 'sC > @hind.D', '5h', 1),
        C('chain', 'Harrier loop', 'sC > @hind.D > @harrier.D', '6h', 2),
        C('corner', 'Harrier loop', 'sC > @hind.D > @harrier.B > (C)', '8h', 2),
        C('corner', 'Rolling Thunder', 'sC > @hind.D (2) > @harrier.D > df+D > (C)', '5h', 2),
        C('chain', 'The Hind', 'sC > @hind.D (2) > @harrier.D > @hind.B', '5h', 2),
        C('super', 'Many Torpedo', 'sC > @hind.D (2) > @harrier.D > @torpedo', '10h', 2),
        C('super', 'Aurora', 'sC > @hind.D (2) > @harrier.D > @aurora > (C)', '14h', 2),
        C('dc', 'DC → An Oi', 'sC > @hind.D (2) > @harrier.D > @torpedo (DC) > @anoi', '17h', 3),
        C('super', 'Many Torpedo', 'sC > @torpedo', '8h', 1),
        C('super', 'Aurora', 'sC > @aurora', '12h', 1),
        C('dc', 'DC → An Oi', 'sC > @torpedo (DC) > @anoi', '15h', 3),
        C('bnb', 'Crazy Ivan', 'fC > sC > @ivan.A > (C)', '3h', 1),
        C('super', 'Many Torpedo', 'fC > sC > @ivan.A (SC) > @torpedo', '10h', 2),
        C('dc', 'DC → An Oi', 'fC > sC > @ivan.A (SC) > @torpedo (DC) > @anoi > (C)', '17h', 3),
        C('bnb', 'Gulf Tomahawk', 'fC > sC > @gulf.B', '3h', 1),
        C('bnb', 'Gulf Tomahawk', 'fC > sC > @gulf.B > (C)', '4h', 1),
        C('bnb', 'The Hind', 'fC > sC > @hind.B > (C)', '5h', 1),
        C('bnb', 'The Hind', 'fC > sC > @hind.D', '6h', 1),
        C('chain', 'Harrier loop', 'fC > sC > @hind.D > @harrier.B', '7h', 2),
        C('corner', 'Rolling Thunder', 'fC > sC > @hind.D (2) > @harrier.D > df+D > (C)', '6h', 2),
        C('chain', 'The Hind', 'fC > sC > @hind.D (2) > @harrier.D > @hind.B', '6h', 2),
        C('super', 'Many Torpedo', 'fC > sC > @hind.D (2) > @harrier.D > @torpedo', '11h', 2),
        C('dc', 'DC → An Oi', 'fC > sC > @hind.D (2) > @harrier.D > @torpedo (DC) > @anoi', '18h', 3),
        C('bnb', 'Crazy Ivan', 'cC > @ivan.A', '2h', 1),
        C('super', 'Many Torpedo', 'cC > @ivan.A (SC) > @torpedo', '9h', 2),
        C('super', 'Aurora', 'cC > @ivan.A (SC) > @aurora', '12h', 2),
        C('dc', 'DC → An Oi', 'cC > @ivan.A (SC) > @torpedo (DC) > @anoi > (C)', '16h', 3),
        C('bnb', 'Gulf Tomahawk', 'cC > @gulf.B', '3h', 1),
        C('bnb', 'The Hind', 'cC > @hind.B', '4h', 1),
        C('bnb', 'The Hind', 'cC > @hind.D', '5h', 1),
        C('chain', 'Harrier loop', 'cC > @hind.D > @harrier.D', '6h', 2),
        C('corner', 'Harrier loop', 'cC > @hind.D > @harrier.B > (C)', '8h', 2),
        C('corner', 'Rolling Thunder', 'cC > @hind.D (2) > @harrier.D > df+D > (C)', '5h', 2),
        C('chain', 'The Hind', 'cC > @hind.D (2) > @harrier.D > @hind.B', '5h', 2),
        C('super', 'Many Torpedo', 'cC > @hind.D (2) > @harrier.D > @torpedo', '10h', 2),
        C('super', 'Aurora', 'cC > @hind.D (2) > @harrier.D > @aurora > (C)', '14h', 2),
        C('dc', 'DC → An Oi', 'cC > @hind.D (2) > @harrier.D > @torpedo (DC) > @anoi', '17h', 3),
        C('super', 'Many Torpedo', 'cC > @torpedo', '8h', 1),
        C('super', 'Aurora', 'cC > @aurora', '12h', 1),
        C('dc', 'DC → An Oi', 'cC > @torpedo (DC) > @anoi', '15h', 3),
        C('super', 'Aurora', '@harrier.D > @harrier.D > @aurora > (C)', '13h', 2),
        C('chain', 'Harrier loop', 'jB > @harrier.B', '3/4h', 2),
        C('corner', 'Harrier loop', 'jB > @harrier.B > (C)', '5h', 2),
        C('corner', 'The Hind', 'jB > @harrier.D > (land) > @hind.B > (C)', '5h', 2),
        C('super', 'Many Torpedo', 'jB > @harrier.D > (land) > @torpedo > (C)', '10h', 2),
        C('super', 'Aurora', 'jB > @harrier.D > (land) > @aurora > (C)', '14h', 2),
        C('dc', 'DC → An Oi', 'jB > @harrier.D > (land) > @torpedo (DC) > @anoi > (C)', '17h', 3),
        C('bnb', 'The Hind', 'shC > cB > cB > @hind.B', '7h', 1),
        C('super', 'Aurora', 'shC > sA > sC > @hind.D (2) > @harrier.D > @aurora > (C)', '17h', 2),
        C('dc', 'DC → An Oi', 'shC > cC > @hind.D (2) > @harrier.D > @torpedo (DC) > @anoi', '19h', 3),
        C('dc', 'DC → An Oi', 'shC > sA > sC > @hind.D (2) > @harrier.D > @torpedo (DC) > @anoi', '20h', 3),
        C('dc', 'DC → An Oi', 'jD > sA > sC > @hind.D (2) > @harrier.D > @torpedo (DC) > @anoi', '19h', 3),
        C('bnb', 'The Hind', '@buffrass.A > cB > @hind.B > (C)', '7h', 1),
        C('dc', 'DC → An Oi', '@buffrass.A > sA > sC > @hind.D (2) > @harrier.D > @torpedo (DC) > @anoi > (C)', '21h', 3),
        C('super', 'Many Torpedo', '@buffrass.A > @torpedo', '10h', 1),
        C('dc', 'DC → An Oi', '@buffrass.A > @torpedo (DC) > @anoi', '17h', 3),
        C('bnb', 'Normal chain', 'cxD > sA > sD', '4h', 1),
        C('counter', 'Normal chain', 'jCD > jCD', '2h', 1),
        C('counter', 'Normal chain', 'jCD > sCD', '2h', 1),
        C('counter', 'Rolling Thunder', 'jCD > df+D', '2h', 1),
        C('counter', 'Aurora', 'jCD > @aurora', '11h', 1),
        C('counter', 'Harrier loop', 'jCD > @harrier.B > (C)', '4h', 2),
        C('counter', 'Gulf Tomahawk', 'jCD > @gulf.B', '3h', 1),
        C('counter', 'Gulf Tomahawk', 'jCD > @gulf.B > (C)', '4h', 1),
        C('counter', 'The Hind', 'jCD > @hind.D', '2h', 1),
        C('counter', 'The Hind', 'jCD > @hind.D > (C)', '5h', 1),
        C('counter', 'The Hind', 'sCD > @hind.B', '3h', 1),
        C('counter', 'Gulf Tomahawk', 'sCD > @gulf.B', '3h', 1),
        C('counter', 'Many Torpedo', 'sCD > @torpedo', '8h', 1),
        C('counter', 'Normal chain', 'sCD @aurora', '12h', 1),
        C('counter', 'DC → An Oi', 'sCD > @torpedo (DC) > @anoi', '15h', 3),
        C('counter', 'Aurora', '@ivan.A > @aurora > (C)', '12h', 1),
    ]
