# -*- coding: utf-8 -*-
"""Combo dataset for the MvC2 Cammy/BB Hood/Cyclops combo guide.
Sources (GameFAQs, read via Wayback): Cammy 7669 Johmeriquai, 22878 The_fireboy,
8517 ABrea; BB Hood 8318 G-Boy; Cyclops 7893 Z-Force, 7945 PhatDan81, 9838 TBui;
plus the sibling beginner guide (core=True). Old 6-button FAQ notation normalised
to MvC2's real LP/LK/HP/HK (no medium button); true duplicates folded."""
from gen import G, GP, GC, JG, M, MA, DB, CH, SQ, DIR, SP, PRE, TAG

# use-case groups, in display order
GROUPS = [
    ('bnb',    'Ground BnB — meterless'),
    ('aa',     'Anti-air &amp; quick confirms'),
    ('super',  'Hit-confirm into Super (1 bar)'),
    ('air',    'Launcher → Aerial Rave'),
    ('otg',    'OTG &amp; relaunch'),
    ('cancel', 'Special-cancel &amp; beam links'),
    ('corner', 'Corner, loops &amp; semi-infinites'),
    ('throw',  'Throws &amp; resets'),
    ('team',   'Team — DHC &amp; assists'),
]

META = {
    'cammy':   {'name': 'Cammy',   'role': 'Rushdown point',  'ca': '#5fd36b'},
    'bbhood':  {'name': 'BB Hood', 'role': 'Zoner / battery',  'ca': '#ff8fa3'},
    'cyclops': {'name': 'Cyclops', 'role': 'Assist anchor',    'ca': '#7cc0ff'},
}
ORDER = ['cammy', 'bbhood', 'cyclops']

# diff: 1 easy / 2 medium / 3 hard.  core=True -> also in the sibling beginner guide.
def C(cid, grp, name, seq, note='', diff=1, core=False, src=''):
    return dict(id=cid, grp=grp, name=name, seq=seq, note=note, diff=diff, core=core, src=src)

COMBOS = {}

# ======================================================= CAMMY
COMBOS['cammy'] = [
 # --- Ground BnB ---
 C('CA-01','bnb','Bread &amp; butter',
   [G('LP','LP','HP'), TAG('XX'), SP('Cannon Drill','QCF','K')],
   'The first thing to learn. Double-jab into fierce, cancel the fierce into the drill.', 1, core=True, src='sibling · ABrea · fireboy'),
 C('CA-02','bnb','Low BnB (OTG-able)',
   [GC('LK','LK','HK'), TAG('XX'), SP('Cannon Drill','QCF','K')],
   'All lows — opens crouchers. The drill knocks down so you can OTG after.', 1, src='ABrea #2 · fireboy'),
 C('CA-03','bnb','Range BnB',
   [G('LP','LP'), DB('B','HK'), TAG('XX'), SP('Cannon Drill','QCF','K')],
   'B+HK has extra reach (you can swap it for standing HP). Great after a poke.', 2, src='ABrea #1'),
 C('CA-04','bnb','Knockdown ender',
   [G('LP','LP','HP'), TAG('XX'), SP('Cannon Spike','DP','K')],
   'Same start, Cannon Spike ender for a hard knockdown / anti-air finish.', 1, src='fireboy'),
 # --- Super confirms ---
 C('CA-05','super','Tap-tap super',
   [G('LP','LP','HP'), TAG('XX'), SP('Spin Drive Smasher','QCF','KK')],
   'The BnB, but end in the super. ~12 hits. Your everyday 1-bar punish.', 1, core=True, src='sibling · ABrea #3 · fireboy'),
 C('CA-06','super','Low into super',
   [GC('LK','LK','HK'), TAG('XX'), SP('Spin Drive Smasher','QCF','KK')],
   '~9 hits. Not every hit of the super connects from lows, but it stays an OTG threat.', 2, src='ABrea #5'),
 C('CA-07','super','Jump-in into super',
   [JG('LP','LP'), PRE('land'), G('LP','LP','HP'), TAG('XX'), SP('Spin Drive Smasher','QCF','KK')],
   'Jump-in adds 2 hits (~14). Confirm the jab string before committing the bar.', 2, core=True, src='sibling · fireboy'),
 C('CA-08','super','Dash low → vertical super',
   [PRE('dash'), GC('LK','HK'), PRE('(pause)'), SP('Reverse Shaft Breaker','QCB','KK')],
   'Pause a tick after the knockdown HK so the rising super catches them.', 2, src='ABrea #9'),
 C('CA-09','super','Cross-up confirm',
   [JG('LK'), TAG('cross-up'), GC('LK'), TAG('XX'), SP('Reverse Shaft Breaker','QCB','KK')],
   'The cross-up only confuses — confirm off the cr.LK before the super.', 2, src='ABrea #7'),
 C('CA-10','super','Knuckle into super',
   [SP('Axel Spin Knuckle','QCF','P'), TAG('1 hit · XX'), SP('Spin Drive Smasher','QCF','KK')],
   'Cancel after just the FIRST hit of the knuckle or the 2nd hit knocks them away.', 3, src='ABrea #11'),
 C('CA-11','super','Easy corner OTG super',
   [PRE('corner'), SP('Reverse Shaft Breaker','QCB','KK'), PRE('(pause)'), GC('LK'), TAG('OTG'),
    PRE('SJ'), G('LP','LK','HP','HK')],
   'In the corner the super leaves them falling in place — her easiest OTG into a rave.', 3, src='ABrea #12'),
 C('CA-12','super','Super → OTG → air',
   [SP('Spin Drive Smasher','QCF','KK'), PRE('dash'), GC('LK'), TAG('OTG'), GC('HP'),
    PRE('SJ'), G('LP','LK','HP','HK')],
   'Spin Drive Smasher is OTG-able: dash, scoop with cr.LK and fly.', 3, src='ABrea #8'),
 # --- Launcher → Aerial Rave ---
 C('CA-13','air','Basic Aerial Rave',
   [DB('D','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP','HK')],
   'Her core air string. Both finishers connect in the corner; wait a beat after HP.', 1, src='ABrea AR#2'),
 C('CA-14','air','Lazy launch ender',
   [G('HK'), TAG('launch'), SP('Cannon Spike','DP','K')],
   '2 hits — for when you are not comfortable air-dashing the rave yet.', 1, src='ABrea AR#1'),
 C('CA-15','air','Raw launch → super',
   [DB('D','HP'), TAG('launch · XX'), SP('Reverse Shaft Breaker','QCB','KK')],
   'No chain before the launcher (it pushes too far). A safety-net super finish.', 1, src='ABrea #10'),
 C('CA-16','air','Aerial Rave → drill',
   [DB('D','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP','HK'), TAG('XX'), SP('Cannon Drill','QCF','K')],
   'Tack the drill onto the end of the rave for the knockdown / OTG follow-up.', 2, core=True, src='sibling'),
 # --- OTG & KBA loops ---
 C('CA-17','otg','★ The KBA combo',
   [DB('D','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP'), TAG('XX'),
    SP('Cannon Drill (HK)','QCF','HK'), TAG('XX'), SP('Killer Bee Assault','QCB','PP',air=True)],
   '11 hits, ~79 dmg — the reason to play Cammy. HK drill lifts them high enough for KBA.', 3, src='ABrea AR#3 · fireboy'),
 C('CA-18','otg','OTG super loop',
   [JG('LP','LP'), PRE('land'), G('LP','LP'), TAG('XX'), SP('Spin Drive Smasher','QCF','KK'),
    PRE('dash · OTG'), DB('D','LK'), DB('D','HP'), TAG('relaunch'), PRE('SJ'), G('LP','LK','HP'),
    TAG('XX'), SP('Cannon Drill','QCF','K'), TAG('XX'), SP('Killer Bee Assault','QCB','PP',air=True)],
   'The big sibling-guide combo: super, OTG relaunch, KBA. Flashy and damaging.', 3, core=True, src='sibling'),
 C('CA-19','corner','Semi-infinite (KBA loop)',
   [DB('D','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP'), TAG('XX'), SP('Cannon Drill (HK)','QCF','HK'),
    TAG('XX'), SP('Killer Bee Assault','QCB','PP',air=True), PRE('dash'), GC('LK'), TAG('OTG'), GC('HP'),
    PRE('SJ'), PRE('repeat…')],
   'Corner only (midscreen tech faster). KBA can connect 3+ times in a row — practice the dash timing.', 3, src='ABrea AR#5'),
 C('CA-20','corner','Double KBA (value)',
   [G('HK'), TAG('launch'), PRE('SJ'), SP('Cannon Drill (HK)','QCF','HK'), TAG('XX'),
    SP('Killer Bee Assault','QCB','PP',air=True), PRE('dash'), GC('LK'), TAG('OTG'), GC('HP'),
    G('LP','LK'), TAG('XX'), SP('Cannon Drill (HK)','QCF','HK'), TAG('XX'),
    SP('Killer Bee Assault','QCB','PP',air=True)],
   'Best damage from 2 bars + a double KBA. First drill is the tight link.', 3, src='ABrea AR#6'),
 C('CA-21','corner','Showy delayed rave',
   [DB('D','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP'), PRE('(delay)'), G('LP'),
    PRE('rejump'), G('LP','LK','HP','HK'), TAG('XX'), SP('Cannon Drill (HK)','QCF','HK'), TAG('XX'),
    SP('Killer Bee Assault','QCB','PP',air=True)],
   '~16 hits. The pause lets you relink an extra LP at the top for an ego-crusher.', 3, src='ABrea AR#4 (Genji)'),
 # --- Throws & resets ---
 C('CA-22','throw','Tick-throw → air',
   [G('LP'), PRE('tick'), DB('F','HP'), TAG('throw'), PRE('dash'), GC('LK'), TAG('OTG'), GC('HP'),
    PRE('SJ'), G('LP','LK','HP','HK')],
   'LP has great range/speed — tick into the HP suplex, then OTG into a rave.', 2, src='ABrea throw#1'),
 C('CA-23','throw','Throw loop (corner)',
   [DB('D','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP','HK'), PRE('land'), DB('F','HP'),
    TAG('throw'), GC('LK'), TAG('OTG'), GC('HP'), PRE('SJ'), PRE('repeat…')],
   'Chain the rave slowly so you land in throw range, suplex, OTG, repeat.', 3, src='ABrea throw#2 (Joey)'),
 C('CA-24','throw','Counter bait',
   [PRE('on block'), SP('Cannon Revenge','HCB','P'), TAG('counter')],
   'After a blocked jump-in, the counter snags their mashed poke. Do not overuse — it is readable.', 2, src='fireboy tips'),
]

# ======================================================= BB HOOD
COMBOS['bbhood'] = [
 # --- Ground BnB ---
 C('BB-01','bnb','Bread &amp; butter',
   [G('LP','LK','HP'), TAG('XX'), SP('Shyness Strike','QCB','P')],
   'Magic series into the basket — a clean knockdown to start her keep-away.', 1, core=True, src='sibling'),
 C('BB-02','bnb','Poke into flame',
   [GC('LP'), TAG('XX'), SP('Cheer &amp; Fire','DP','K')],
   'Her best chip combo — cheap, fast, safe on block. Spammable in keep-away.', 1, src='G-Boy Chip&amp;easy'),
 C('BB-03','bnb','Jump-in chip',
   [JG('LK'), TAG('XX'), SP('Cheer &amp; Fire','DP','K')],
   'Air-to-ground version of the chip combo. Good stagger pressure.', 1, src='G-Boy Chip&amp;easy'),
 C('BB-05','bnb','Meterless kick string',
   [JG('LK'), GC('LK'), GC('HK')],
   'Her honest "no-meter" route — ends in a knockdown to reset spacing.', 1, src='G-Boy K&amp;'),
 # --- Anti-air ---
 C('BB-04','aa','Anti-air flame',
   [G('LP','LK'), TAG('XX'), SP('Cheer &amp; Fire','DP','P')],
   'The P version angles up and multi-hits — her answer to air approaches.', 1, src='G-Boy'),
 # --- Super confirms ---
 C('BB-06','super','Chain into super',
   [G('LP','LK','HP'), TAG('XX'), SP('Cool Hunting','QCF','PP')],
   'The BnB into 52-hit Cool Hunting. Enormous block damage even if they guard.', 1, core=True, src='sibling · G-Boy'),
 C('BB-07','super','Basket → super',
   [SP('Shyness Strike','QCB','P'), TAG('XX'), SP('Cool Hunting','QCF','PP')],
   'Cancel the basket straight into guns if the basket connects or is blocked.', 1, src='G-Boy others'),
 C('BB-08','super','Flame → super',
   [SP('Cheer &amp; Fire','DP','P'), TAG('XX'), SP('Cool Hunting','QCF','PP')],
   'Confirm an anti-air flame into the gun super for real damage.', 2, src='G-Boy others'),
 C('BB-09','super','Missile catch → super',
   [SP('Smile &amp; Missile','[B]F','HP'), TAG('knocks down · XX'), SP('Cool Hunting','QCF','PP')],
   'HP missile floats them — wait for the missile to HIT, then super (it eats the missile).', 3, src='G-Boy others'),
 C('BB-10','super','Basket → big super',
   [SP('Shyness Strike','QCB','P'), TAG('XX'), SP('Beautiful Memory','HCF','KK')],
   'Alternate ender — Beautiful Memory does huge damage but whiffs hard if dropped.', 2, src='G-Boy others'),
 C('BB-11','super','Signature: basket super-cancel',
   [G('LP','LK','HP'), TAG('XX'), SP('Shyness Strike','QCB','P'), TAG('XX'), SP('Cool Hunting','QCF','PP')],
   'Chain, basket, THEN super-cancel the basket into guns — her staple bar combo.', 2, core=True, src='sibling'),
 # --- Launcher → Aerial Rave ---
 C('BB-12','air','Aerial Rave',
   [DB('DF','HK'), TAG('launch'), PRE('SJ'), G('LP','LK','HP','HK'), TAG('XX'),
    SP('Cheer &amp; Fire','DP','K',air=True)],
   'Her air combos are minor (short reach) but the air-flame ender knocks down.', 2, core=True, src='sibling'),
 C('BB-13','air','Double-jump rave',
   [DB('DF','HK'), TAG('launch'), PRE('SJ'), G('LP','LK'), PRE('dj'), G('LP','LK'), TAG('XX'),
    SP('Cheer &amp; Fire','DP','K',air=True)],
   'Use her double jump to add hits when the basic rave drops them too soon.', 3, src='G-Boy A&amp;C'),
 # --- OTG ---
 C('BB-14','otg','Corner missile OTG',
   [GC('LP'), GC('LK'), GC('HP'), TAG('XX'), SP('Smile &amp; Missile','[B]F','HP'),
    PRE('dash · OTG'), G('LK'), DB('DF','HK'), TAG('relaunch'), PRE('SJ'), G('LP','LK','HP')],
   'Corner: HP missile knocks down, dash in and OTG into a fresh launch + rave.', 3, src='G-Boy OTG&amp;'),
 # --- Team / DHC ---
 C('BB-16','team','Battery → DHC',
   [G('LP','LK','HP'), TAG('XX'), SP('Cool Hunting','QCF','PP'), PRE('DHC'),
    SP('Mega Optic Blast','QCF','PP'), TAG('Cyclops')],
   'BB Hood builds meter fast — cash it into Cyclops’ Mega Optic Blast for a team kill.', 2, core=True, src='sibling'),
 C('BB-17','team','Anchor cover',
   [SP('Cool Hunting','QCF','PP'), PRE('DHC'), SP('Spin Drive Smasher','QCF','KK'), TAG('Cammy')],
   'If Cammy is alive behind her, DHC the guns into Spin Drive Smasher instead.', 2, src='team'),
 # --- Resets / mixups ---
 C('BB-18','throw','Unblockable grab',
   [SP('Hyper Apple For You','HCB','KK'), TAG('command grab')],
   'Against turtles who just block — the grab super beats guarding outright.', 2, src='G-Boy supers'),
 C('BB-19','throw','Crawl mix-up',
   [SP('Stalking','D,D','KK'), TAG('crawl under'), PRE('cross-up'), G('LP','LK','HP')],
   'Crawl under a fireball / super, come out the other side into the BnB.', 2, src='G-Boy'),
]

# ======================================================= CYCLOPS
COMBOS['cyclops'] = [
 # --- Ground BnB ---
 C('CY-01','bnb','Bread &amp; butter',
   [G('LP','LK','HK'), TAG('XX'), SP('Cyclone Kick','QCB','K')],
   'His magic series into Cyclone Kick — easy, safe, knocks down.', 1, core=True, src='sibling · TBui #3'),
 C('CY-02','bnb','Sweep knockdown',
   [G('LP','LK','HK'), TAG('XX'), SP('Optic Sweep','F-DF-D','P')],
   'Sweep ender lays them flat AND keeps them OTG-able for a super.', 1, src='TBui #4 · PhatDan #21'),
 C('CY-03','bnb','Low BnB',
   [GC('LK','HK'), TAG('XX'), SP('Cyclone Kick','QCB','K')],
   'Two lows into the kick — opens crouch-blockers. OTG-able knockdown.', 1, src='PhatDan #25'),
 C('CY-04','bnb','Crouch fierce route',
   [GC('LK','HP'), TAG('XX'), SP('Cyclone Kick','QCB','K')],
   'cr.HP has more push — use when slightly farther out.', 2, src='PhatDan #11'),
 # --- Anti-air & quick confirms ---
 C('CY-06','aa','Jab anti-air',
   [G('LP'), TAG('XX'), SP('Gene Splice','DP','P')],
   'Tag a jumper with jab, mash Gene Splice. Mashing adds hits.', 1, src='PhatDan #1 · TBui'),
 C('CY-07','aa','Two-hit into DP',
   [G('LP','LK'), TAG('XX'), SP('Gene Splice','DP','P')],
   'Slightly longer confirm into the uppercut.', 1, src='PhatDan #4'),
 C('CY-08','aa','Two-hit into kick',
   [G('LP','LK'), TAG('XX'), SP('Cyclone Kick','QCB','K')],
   'Lower-commitment knockdown when Gene Splice would whiff.', 1, src='PhatDan #5'),
 C('CY-09','aa','Jab into grab',
   [G('LP'), TAG('XX'), SP('Optic Hold','F-DF-D-DB-B','P')],
   'Tick the jab into his command grab for a throw they cannot mash out of.', 2, src='PhatDan #2'),
 C('CY-10','aa','Poke into beam',
   [PRE('far'), GC('HP'), TAG('XX'), SP('Optic Blast','QCF','LP')],
   'Long-range cr.HP cancels into the jab beam — a safe footsie confirm.', 2, src='PhatDan #6'),
 # --- Super confirms ---
 C('CY-11','super','Chain into super',
   [G('LP','LK','HK'), TAG('XX'), SP('Mega Optic Blast','QCF','PP')],
   'The BnB into his screen-filling beam super. Low recovery, easy to land.', 1, core=True, src='sibling · TBui #6'),
 C('CY-12','super','Chain into aimed super',
   [G('LP','LK','HK'), TAG('XX'), SP('Super Optic Blast','QCF','KK')],
   'Same string, controllable beam — angle it if they tried to jump out.', 1, src='PhatDan #23'),
 C('CY-13','super','Low OTG super',
   [GC('LK','HK'), TAG('XX'), SP('Mega Optic Blast','QCF','PP'), TAG('OTG')],
   'cr.HK knocks down and the beam OTGs them as they hit the floor.', 2, src='PhatDan #28'),
 C('CY-14','super','Low OTG aimed super',
   [GC('LK','HK'), TAG('XX'), SP('Super Optic Blast','QCF','KK'), TAG('OTG')],
   'Aimable-beam version of the low OTG.', 2, src='PhatDan #27'),
 # --- Special-cancel & beam links (his signature) ---
 C('CY-16','cancel','Cyclone → super',
   [G('LP','LK','HK'), TAG('XX'), SP('Cyclone Kick','QCB','K'), TAG('XX'), SP('Mega Optic Blast','QCF','PP')],
   'Cancel the Cyclone Kick into the beam — time it as the kick connects.', 2, core=True, src='sibling · TBui #11'),
 C('CY-17','cancel','Cyclone → air super',
   [G('LP','LK','HK'), TAG('XX'), SP('Cyclone Kick','QCB','K'), TAG('XX'),
    SP('Super Optic Blast','QCF','KK',air=True)],
   'Cancel into the AIR beam super for a different angle / juggle.', 3, src='PhatDan #34'),
 C('CY-18','cancel','Sweep OTG → super',
   [G('LP','LK','HK'), PRE('OTG'), SP('Optic Sweep','F-DF-D','P'), PRE('XX'), SP('Mega Optic Blast','QCF','PP')],
   'Sweep knocks down low, then OTG the beam super for big damage.', 2, core=True, src='sibling · PhatDan #37'),
 C('CY-19','cancel','Sweep OTG → aimed super',
   [G('LP','LK','HK'), PRE('OTG'), SP('Optic Sweep','F-DF-D','P'), PRE('XX'), SP('Super Optic Blast','QCF','KK')],
   'Aimable-beam version of the sweep OTG.', 2, src='PhatDan #36'),
 C('CY-20','cancel','Beam → uppercut link',
   [GC('LK'), G('HK'), TAG('2-hit · XX'), SP('Optic Blast','QCF','HP'), TAG('XX'), SP('Gene Splice','DP','P')],
   'His coolest link: the HP beam recovers fast enough to dragon-punch after it.', 3, src='PhatDan #26/#41'),
 C('CY-21','cancel','Beam → uppercut → air super',
   [GC('LK'), G('HK'), TAG('2-hit · XX'), SP('Optic Blast','QCF','HP'), TAG('XX'), SP('Gene Splice','DP','P'),
    TAG('XX'), SP('Super Optic Blast','QCF','KK',air=True), TAG('aim up')],
   'Extend the beam→DP link into an air super for a meter-heavy juggle.', 3, src='PhatDan #45'),
 C('CY-15','cancel','Beam → super',
   [G('LP','LK','HK'), TAG('XX'), SP('Optic Blast','QCF','HP'), TAG('XX'), SP('Super Optic Blast','QCF','KK')],
   'String into the HP beam, then super-cancel the beam itself.', 3, src='PhatDan #33'),
 # --- Launcher → Aerial Rave ---
 C('CY-22','air','Aerial Rave (6-hit)',
   [G('LP','LP'), DB('DF','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','LP','LK','HK','HK')],
   'His long air string — the double-HK ender uses his double-kick.', 2, core=True, src='sibling'),
 C('CY-23','air','Standard rave',
   [G('LP','LK','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP','HK')],
   'The universal air rave — HP (S.Strong) doubles as the launcher here.', 1, src='PhatDan #17'),
 C('CY-24','air','Jump-in air combo',
   [JG('HK'), G('LP','LK','HP'), TAG('XX'), SP('Gene Splice','DP','P')],
   'Deep jumping HK, ground chain, mash Gene Splice for the knockdown.', 2, src='PhatDan #7'),
 C('CY-25','air','Double-jump rave',
   [G('LP','LK','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP','LP','LK','HP'), PRE('dj'),
    G('LP','LK','HP','HK')],
   'Use his double jump to stack a second air string — long and stylish.', 3, src='PhatDan #19'),
 # --- Corner / Running Tackle ---
 C('CY-26','corner','Tackle OTG → kick',
   [SP('Running Tackle','[B]F','K'), GC('LK'), TAG('OTG'), G('HK'), TAG('1-hit · XX'), SP('Cyclone Kick','QCB','K')],
   'Unblockable tackle starts it; OTG cr.LK, one HK hit, cancel the kick.', 2, src='PhatDan #40'),
 C('CY-27','corner','Tackle → beam → DP',
   [SP('Running Tackle','[B]F','K'), GC('LK'), TAG('OTG'), G('HK'), TAG('2-hit · XX'),
    SP('Optic Blast','QCF','HP'), TAG('XX'), SP('Gene Splice','DP','P')],
   'The tackle into his beam→uppercut link — big midscreen-to-corner damage.', 3, src='PhatDan #42'),
 C('CY-28','corner','Tackle → super',
   [SP('Running Tackle','[B]F','K'), GC('LK'), TAG('OTG'), G('HK'), TAG('2-hit · XX'),
    SP('Super Optic Blast','QCF','KK')],
   'Simpler tackle route straight into the aimable beam.', 2, src='PhatDan #43'),
 C('CY-29','corner','Tackle → full link → air super',
   [SP('Running Tackle','[B]F','K'), GC('LK'), TAG('OTG'), G('HK'), TAG('2-hit · XX'),
    SP('Optic Blast','QCF','HP'), TAG('XX'), SP('Gene Splice','DP','P'), TAG('XX'),
    SP('Super Optic Blast','QCF','KK',air=True), TAG('aim up')],
   'Everything: tackle, beam, uppercut, air super. His max-damage corner punish.', 3, src='PhatDan #46'),
 C('CY-30','corner','Corner air loop',
   [JG('HP'), G('LP','LK','HP'), TAG('launch'), PRE('SJ'), G('LP','LK','HP','LP','LK','HP'), PRE('dj'),
    G('LP','LK','HP','LP','LK','HP','HK'), DB('D','LK'), TAG('OTG'), GC('LP','HP'), G('HK')],
   'The full corner showcase: double-jump air loop into an OTG ground re-chain.', 3, src='PhatDan #38'),
 # --- Team / DHC ---
 C('CY-31','team','The DHC ender',
   [PRE('any super'), PRE('DHC'), SP('Mega Optic Blast','QCF','PP')],
   'Mega Optic Blast is the team’s closer — DHC any partner super into it.', 1, core=True, src='sibling'),
 C('CY-32','team','Charge punches → super',
   [SP('Charging Punches','[B]F','P'), TAG('mash · XX'), SP('Mega Optic Blast','QCF','PP')],
   'Surprise charge tackle, mash the punches, cancel into the beam.', 2, src='Z-Force'),
]
